/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "auth",
            "endpoint": "https://pk4f8g5bpi.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:0c847873-5a03-496c-a720-b1d64474f6a5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o5kjGq22M",
    "aws_user_pools_web_client_id": "4f3v8jemls54s18ermof5f132p",
    "oauth": {},
    "aws_user_files_s3_bucket": "dlnresources182402-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
