export { default as logoDark } from './DLN-dark.png';
export { default as alphaFin2 } from './Alphafin2.png';
export { default as BS } from './BS.png';
export { default as Casper } from './Casper.png';
export { default as CoinSqad } from './CoinSqad.png';
export { default as Drapper } from './Drapper.png';
export { default as Giftz } from './Giftz.png';
export { default as PD } from './PD.png';
export { default as Rivet } from './Rivet.png';
export { default as Totle } from './Totle.png';
export { default as WDBT } from './WDBT.png';
export { default as wishKnish } from './wishKnish.png';
export { default as Right_Arrow } from './Right_Arrow.png';
export { default as Left_Arrow } from './Left_Arrow.png';
export { default as SmallLogo } from './smlLogo.png';
export { default as VideoThumbnail1 } from './videoThumbnail1.png'
export { default as VideoThumbnail2 } from './videoThumbnail2.png'
export { default as DCBSLogo } from './dcbsLogo.png'
export { default as AfgahnOrg } from './afghanOrg.png'
export { default as HelpSl } from './helpSl.png'
export { default as Questscope } from './questscope-circle.png'

// landing page

export { default as DLNLogo } from '../Images/DLN-Logo.png';
export { default as DLNLHeroRight } from '../Images/Hero_Dln_Glass.png';
export { default as Borrower } from '../Images/Borrower2.png';
export { default as Investor } from '../Images/Investor.png';
export { default as Lenders } from '../Images/Lenders.png';
export { default as SocialStaking } from '../Images/SocialStaking.png';
export { default as SocialStakingSmall } from '../Images/SocialStaking_small.png';
export { default as Money } from '../Images/Money.png';
export { default as Social } from '../Images/Social.png';
export { default as Investors } from '../Images/Investors.png';
export { default as Proposal } from '../Images/Proposal.png';
export { default as Token } from '../Images/Token.png';
export { default as Assets } from '../Images/Assets.png';
export { default as ArrowWithHeads } from '../Images/Arrow.png';
export { default as Arrow } from '../Images/Arrow_1.png';
export { default as DLN_Community } from '../Images/DLN_Community.png';
export { default as Factory } from '../Images/Factory.png';
export { default as Casper2 } from './casper2.png';
export { default as CasperLabs } from './Casperlabs.jpg';
